#!/bin/bash


# Get the absolute path of the root of the repository
repo_root=$(git rev-parse --show-toplevel)

# Check if _version.py has been modified
if git diff --quiet HEAD~1 HEAD -- "${repo_root}/src/yogic/_version.py"; then
    # _version.py hasn't been modified; do nothing
    exit 0
fi

# Extract the version number from _version.py
version=$(python -c "import yogic; print(yogic.__version__)")

echo "XXXXXXXXXXXXXXXXXXXXXXX - $version"

# Create a Git tag with the version number
if git tag -l | grep -q "^$version$"; then
    echo "Tag $version already exists"
    exit 1
else
    git tag -a "$version" -m "Version $version"
fi
