#!/bin/bash

# Extract the version number:
version=$(python -c "import yogic; print(yogic.__version__)")

# Create a Git tag with the version number
if git tag -l | grep "^$version$"; then
    echo "pre-commit hook: Nothing to do. Tag $version already exists."
    exit 0
else
    echo "pre-commit hook: Adding new tag $version"
    git tag -a "$version" -m "Version $version"
fi
