#!/bin/bash

# Get the absolute path of the root of the repository
repo_root=$(git rev-parse --show-toplevel)

# Extract the version number from _version.py
version=$(python -c "import yogic; print(yogic.__version__)")
# Create a Git tag with the version number
if "$(git describe --tags --abbrev=0)"=="$version"; then
    echo "Tag $version already exists"
    exit 1
else
    git tag -a "$version" -m "Version $version"
fi
