# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.2.3.dev0+g031cd8d.d20230626'
__version_tuple__ = version_tuple = (0, 2, 3, 'dev0', 'g031cd8d.d20230626')
