# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.3.2.dev54+g6432a3f.d20230830'
__version_tuple__ = version_tuple = (0, 3, 2, 'dev54', 'g6432a3f.d20230830')
