# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.2.9.dev12+gb09d9b0.d20230716'
__version_tuple__ = version_tuple = (0, 2, 9, 'dev12', 'gb09d9b0.d20230716')
